name: pull-request
on:
  pull_request:
jobs:
  pull-request:
    name: Pull request requires changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check that changelog updated
        run: |
          if ! grep --quiet CHANGELOG.md <(git diff --name-only $GITHUB_REF $(git merge-base $GITHUB_REF main))
          then
            echo "ERROR - Commit failed"
            echo "Changelog must be included with pull request."
            exit 1
          fi

